language: python
python:
  - "3.6"   # this is just for travis

services:
  - docker

before_script: pip install docker-compose

script:
  # this script runs everytime we push a change in github (run tests and flake8 linter)
  - docker-compose run app sh -c "python manage.py test && flake8"